[repository]
commit_pins = [
  [
    "b07770b9ef1cceb2e6f56d33538aaffb9186b9c",
    "b96d88f5bb5383e9ed474cb6db36f4298de697a6",
  ], # 0.3.3 for 0.54.1b
]
name = "Ergons_shitty_plugins"
authors = ["Ergon"]
[alttab]
description = "Alttab for hyprland"
authors = ["Ergon"]
output = "alttab.so"
build = ["make release"]
